version: '3.8'

services:
  meo-stationery:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./prisma/dev.db
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-production-secret-key
    volumes:
      # Mount a volume for the SQLite database to persist data
      - sqlite_data:/app/prisma
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - meo-network

  meo-monitor:
    build: ./monitoring
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - MEO_APP_URL=http://meo-stationery:3000
    volumes:
      # Mount Docker socket for container monitoring
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Persist monitoring database
      - monitor_data:/app/data
      # Mount host system for system monitoring
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro
    restart: unless-stopped
    depends_on:
      - meo-stationery
    networks:
      - meo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  sqlite_data:
  monitor_data:

networks:
  meo-network:
    driver: bridge
